# Project information
site_name: API Requirements for Dutch Healthcare
site_description: Requirements for Application Programming Interfaces (APIs) in Dutch Healthcare.
site_author: Nictiz
site_url: https://nictiz.github.io/api-requirements-docs/

# Repository
repo_url: https://github.com/nictiz/api-requirements-docs
edit_uri: blob/main/docs/

# Navigation
nav:
  - 'Overview': index.md
  - 'Introduction': introduction.md
  - 'Notational Conventions': notational-conventions.md
  - 'Definitions and scope': definitions-and-scope.md
  - 'API specification & documentation': api-specification-and-documentation.md
  - 'API testability': api-testability.md
  - 'API discoverability': api-discoverability.md
  - 'API onboarding': api-onboarding.md
  - 'API Lifecycle management and versioning': api-lifecycle-management-and-versioning.md
  - 'API agreements': api-agreements.md
  - 'API design rules': api-design-rules.md
  - 'API security': api-security.md
  - 'Health Information Standards compliance': health-information-standards-compliance.md
  - 'Contributing': contributing.md
  
# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.view
    - content.action.edit
  font:
    text: Roboto
    code: JetBrains Mono

extra:
  # Version provider
  # Default version is identified by the `latest` alias
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better.
  analytics:
    provider: google
    property: G-GYNT85534L
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSe6fE2LxSBPYYKa-qFGkCOp265BpPPuQIq4l0w8NWqXeUKyGg/viewform?entry.816166561={url}" target="_blank" rel="noopener">telling us what you're missing</a>.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nictiz/

copyright: >-
  Copyright &copy; 2023 Nictiz | <a href="#__consent">Change cookie settings</a> |
  <a href="https://nictiz.nl/privacy-statement" target="_blank" rel="noopener">Privacy statement</a>

# Extensions
plugins:
  - search
  - mike:
      canonical_version: latest